### ISSUE TITLE
Spec panel is resizing when spec is clicked

### ISSUE THREAD

**Issue by mahendrakariya** [getgauge/html-report#53]
### Expected behavior

Specification panel on the left should not be resized when user clicks on spec.
### Actual behavior

Specification panel on the left is getting resized.

This is how the screen looks like when we open the reports.
![image](https://cloud.githubusercontent.com/assets/2538874/14418080/6123e138-ffd9-11e5-95dd-c7ffe747c59a.png)

The screen turns to this when we click on the `Execution hooks failing` specification in the left hand side panel.
![image](https://cloud.githubusercontent.com/assets/2538874/14418110/8e18686c-ffd9-11e5-912c-1fddf8387be6.png)
### Gauge version

```
Gauge version: 0.4.1

Plugins
-------
html-report (2.1.0)
java (0.3.4)
ruby (0.1.1)
```

[reports-ruby.zip](https://github.com/getgauge/html-report/files/212358/reports-ruby.zip)

**Comment by mahendrakariya** [comment]
This is fixed with the rewrite.

**Comment by sguptatw** [comment]
Re-sizing is still happening. Execute this project and in the report check by toggling on the spec names.
[LongSpecNames.zip](https://github.com/getgauge/html-report/files/582595/LongSpecNames.zip)
